version: "3"
services:
 app:
  build: .
  restart: always
  command: npm run dev
  volumes:
   - ./log:/usr/app/log
   - ./src:/usr/app/src
   - ./database/log:/usr/app/database/log
  ports:
    - ${PORT}:${PORT}
  depends_on:
    - postgres

 postgres:
  build: ./database/
  restart: always
  ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
  environment:
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_DB: ${POSTGRES_DB}